#!/usr/bin/env bun
//! Walks `web/node_modules` and emits a markdown section of every npm
//! dependency, its license, and the verbatim license text.
//!
//! Run as `bun --bun scripts/web-licenses.ts` from the repo root.
//! Pairs with `cargo about generate about.hbs` to produce the
//! Rust half; concatenate the two outputs into THIRD_PARTY_LICENSES.md.

import { readFileSync, readdirSync, statSync, existsSync } from 'fs';
import { join } from 'path';

const WEB_ROOT = join(import.meta.dir, '..', 'web');
const NODE_MODULES = join(WEB_ROOT, 'node_modules');

interface Pkg {
  name: string;
  version: string;
  license: string;
  repository?: string;
  licenseText?: string;
}

function* walkPackageJsons(root: string): Generator<string> {
  for (const entry of readdirSync(root)) {
    const fp = join(root, entry);
    if (entry === '.bin' || entry === '.cache' || entry === '.ignored') continue;
    let st;
    try { st = statSync(fp); } catch { continue; }
    if (!st.isDirectory()) continue;
    if (entry.startsWith('@')) {
      // Scoped namespace; recurse one level.
      for (const sub of readdirSync(fp)) {
        const subFp = join(fp, sub);
        const pj = join(subFp, 'package.json');
        if (existsSync(pj)) yield pj;
      }
    } else {
      const pj = join(fp, 'package.json');
      if (existsSync(pj)) yield pj;
    }
  }
}

function findLicenseText(pkgDir: string): string | undefined {
  const candidates = readdirSync(pkgDir).filter((f) => /^license/i.test(f));
  for (const c of candidates) {
    try {
      const txt = readFileSync(join(pkgDir, c), 'utf8');
      if (txt.trim().length > 0) return txt;
    } catch {
      // ignore
    }
  }
  return undefined;
}

const seen = new Set<string>();
const pkgs: Pkg[] = [];
for (const manifestPath of walkPackageJsons(NODE_MODULES)) {
  try {
    const m = JSON.parse(readFileSync(manifestPath, 'utf8'));
    if (!m.name || !m.version) continue;
    const key = `${m.name}@${m.version}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const license =
      typeof m.license === 'string'
        ? m.license
        : m.license?.type ?? '(unknown)';
    const repo =
      typeof m.repository === 'string'
        ? m.repository
        : m.repository?.url;
    pkgs.push({
      name: m.name,
      version: m.version,
      license,
      repository: repo?.replace(/^git\+/, '').replace(/\.git$/, ''),
      licenseText: findLicenseText(manifestPath.replace(/\/package\.json$/, '')),
    });
  } catch {
    // skip unreadable / malformed
  }
}

// Group by license expression.
const byLicense = new Map<string, Pkg[]>();
for (const p of pkgs) {
  const list = byLicense.get(p.license) ?? [];
  list.push(p);
  byLicense.set(p.license, list);
}

const sorted = [...byLicense.entries()].sort(([a], [b]) => a.localeCompare(b));

const out: string[] = [];
out.push('# Third-party licenses — web dependencies');
out.push('');
out.push(
  'Generated by `bun --bun scripts/web-licenses.ts`. Rerun after every',
);
out.push('`bun install`. Bundled into the binary via `rust-embed`; these');
out.push("notices live alongside the Rust dependencies' THIRD_PARTY_LICENSES.md.");
out.push('');

for (const [license, list] of sorted) {
  out.push(`## ${license}`);
  out.push('');
  list.sort((a, b) => a.name.localeCompare(b.name));
  for (const p of list) {
    const repo = p.repository ? ` — <${p.repository}>` : '';
    out.push(`- **${p.name}** ${p.version}${repo}`);
  }
  out.push('');
  // Pick one representative license text for the group (first one
  // with text available). All same-SPDX-expression packages share the
  // legal terms; the per-file copyright lines vary but the obligations
  // don't.
  const sample = list.find((p) => p.licenseText);
  if (sample?.licenseText) {
    out.push('<details>');
    out.push(`<summary>License text (${sample.name} ${sample.version})</summary>`);
    out.push('');
    out.push('```');
    out.push(sample.licenseText.trimEnd());
    out.push('```');
    out.push('');
    out.push('</details>');
    out.push('');
  }
}

process.stdout.write(out.join('\n'));
